export const ROLE_KEY = ['STD', 'STF', 'FCT'];
export const ROLES = ['student', 'staff', 'faculty', 'common'];

export const MENU_VALUE = ['SITEMAP_MAIN_MENU', 'SITEMAP_HEADER_MENU', 'SITEMAP_FOOTER_MENU'];
export const ROLE_ARRAY = ['STD', 'STF', 'FCT', 'COM'];
export const SITEMAP_POSITION_ARRAY = ['G', 'M', 'H', 'F'];
export const TITLE = ['PROFILE_MY_PROFILE', 'PROFILE_ACADEMIC', 'PROFILE_ACADEMIC', 'STAFF_PROFESSIONAL', 'COMMON_SIGN_OUT', 'MY_CREIGHTON', 'DASH_BOARD_SCHOOL_AND_SEMESTER', 'CLASS_SCHEDULE', 'DASH_BOARD_CAMPUS_DIRECTORY', 'DASH_BOARD_NEXT_EVENTS', 'MISSION_AND_MINISTRY', 'FOOTER_FEEDBACK', 'QUICK_LAUNCH', 'LIBRARY_SEARCH', 'DOIT_SERVICES_AND_SUPPORT'];
