
module.exports = {

FOOTER_ADDRESS : "2500 California Plaza, Omaha, NE 68178",
FOOTER_PHONENUMBER:"402.280.2700",
PHONE_NUMBER : "503.806.2874",
EMAIL : "b140849adb@creighton.edu",
names : [ 'School & Semester','Classes', 'Next Events', 'Mission And Ministry'],
EASYVISTA_URL :'https://creighton-apps.easyvista.com',
STAFFDETAIL_PAGEHEADER : 'Staff Detail',
RESULTS_PAGEHEADER : 'Results',
MYPROFILE_PAGEHEADER : 'My Profile',
ACADEMIC_PAGEHEADER : 'Academic',
LEGALNAME : 'LEGAL NAME',
HOME_ADDRESS : 'HOME ADDRESS',
SCHOOL_ADDRESS :'SCHOOL ADDRESS',
PRIMARY_CONTACT :'PRIMARY CONTACT',
EMERGENCY_CONTACT:'EMERGENCY CONTACT',
EMAIL_HEADER :'EMAIL',
OTHER    :'OTHER',
AGE_OF_MAJORITY : 'IF NOT AGE OF MAJORITY',
ACADEMIC_STATUS :'ACADEMIC STATUS',
ADVISOR_INFORMATION :'ADVISOR INFORMATION'
};




